# Generated by Django 5.0.2 on 2024-02-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slang',
        ),
    ]
