# Generated by Django 5.0.2 on 2024-02-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_slang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='language',
        ),
        migrations.RemoveField(
            model_name='slang',
            name='language',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Grammar',
        ),
        migrations.DeleteModel(
            name='Slang',
        ),
    ]
