# Generated by Django 5.0.2 on 2024-02-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_grammartopic_answer_grammar_slang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
