# Generated by Django 5.0.2 on 2024-02-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0009_grammar_slang_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='grammar_topic',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='language',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Grammar',
        ),
    ]
