# Generated by Django 5.0.2 on 2024-02-27 19:35

import datetime
import django.db.models.deletion
import teach.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('learn', '0003_initial'),
        ('teach', '0010_remove_grammar_creator_remove_grammar_grammar_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100000, validators=[teach.models.validate_answer])),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.question')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_name', models.CharField(max_length=1000, validators=[teach.models.validate_lesson_name])),
                ('grammar_text', models.TextField(max_length=120000, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grammar_topic', models.ForeignKey(choices=[('verbs', 'verbs'), ('nouns', 'nouns'), ('adjectives', 'adjectives'), ('prepositions', 'prepositions'), ('pronouns', 'pronouns'), ('adverbs', 'adverbs')], on_delete=django.db.models.deletion.CASCADE, to='teach.grammartopic', validators=[teach.models.validate_grammar_text])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
