# Generated by Django 5.0.2 on 2024-02-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0011_answer_grammar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grammar',
        ),
    ]
