# Generated by Django 5.0.2 on 2024-02-28 10:52

import django.db.models.deletion
import teach.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('teach', '0014_delete_grammar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_name', models.CharField(max_length=1000, validators=[teach.models.validate_lesson_name])),
                ('grammar_text', models.TextField(max_length=120000, unique=True, validators=[teach.models.validate_grammar_text])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grammar_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.grammartopic')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
