# Generated by Django 5.0.2 on 2024-02-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0017_grammar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
