# Generated by Django 5.0.2 on 2024-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0021_slang_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='slang',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
