# Generated by Django 5.0.2 on 2024-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('info', models.CharField(max_length=12000)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
    ]
